name: digital_oms_sheba
description: "Digital OMS Sheba"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.9.2
  provider: ^6.1.5+1

  # Local Storage & Database
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0
  flutter_cache_manager: ^3.4.1

  # Camera, Scanning & ML
  camera: ^0.12.1

  # Image Editing & Picker
  image_picker: ^1.2.1
  image_cropper: ^12.1.1
  crop_your_image: ^2.0.0
  flutter_image_compress: ^2.4.0

  # UI Components & Media
  flutter_svg: ^2.2.4
  lottie: ^3.3.2
  dropdown_button2: ^3.0.0
  pinput: ^6.0.2
  cached_network_image: ^3.4.1
  shimmer: ^4.0.0

  # Device, System & Permissions
  device_info_plus: ^13.2.0
  network_info_plus: ^8.2.1
  package_info_plus: ^10.2.2
  unique_identifier: ^0.4.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Utilities, Files & Sharing
  intl: ^0.20.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/lottie/
    - assets/images/